name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Build static site
        run: npm install && npm run build
      - name: Deploy static site to S3 bucket
        env:
          AWS_BUCKET: ${{secrets.AWS_BUCKET}}
        run: aws s3 sync ./build/ s3://$AWS_BUCKET --delete
      - name: Clodfront invalidation on AWS
        env:
          DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID}}
        run: aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
      - name: Sending Telegram Message using Bot
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Wetube Frontend is successfully updated on AWS S3.
            Invalidaion on AWS Cloudfront is started.
            Checkou website at - https://wetube.viralsangani.me/